# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  launcher = {
    pname = "launcher";
    version = "2.15.0";
    src = fetchurl {
      url = "https://github.com/project-slippi/slippi-launcher/releases/download/v2.15.0/Slippi-Launcher-2.15.0-x86_64.AppImage";
      sha256 = "sha256-FZyZx/bvtbVR/UJyVcWODP12/6XI5Omp8H5w/61LLds=";
    };
  };
  netplay = {
    pname = "netplay";
    version = "3.6.4";
    src = fetchurl {
      url = "https://github.com/project-slippi/Ishiiruka/releases/download/v3.6.4/FM-Slippi-3.6.4-Linux.zip";
      sha256 = "sha256-yraqKM7lltWuvN1MSCcKceUytvHoSkPr1/qL9S4rH8M=";
    };
  };
  netplay-beta = {
    pname = "netplay-beta";
    version = "4.0.0-mainline-beta.19";
    src = fetchurl {
      url = "https://github.com/project-slippi/dolphin/releases/download/v4.0.0-mainline-beta.19/Mainline-Slippi-4.0.0-mainline-beta.19-Linux.zip";
      sha256 = "sha256-uBPjIjaeLMk68f9uaRytjB60AXcY823ZYm+CfhGwNgk=";
    };
  };
  playback = {
    pname = "playback";
    version = "3.5.2";
    src = fetchurl {
      url = "https://github.com/project-slippi/Ishiiruka-Playback/releases/download/v3.5.2/playback-3.5.2-Linux.zip";
      sha256 = "sha256-x/y6C2EU7qtaogNn2Jpmna7r1jndxDqplpiDsYxJzxw=";
    };
  };
}
