{
  lib,
  pkgs,
  config,
  ...
}:
let
  inherit (lib)
    mkEnableOption
    mkOption
    literalExpression
    types
    mkIf
    ;
  cfg = config.slippi-launcher;
  # Upstream release pins (version + hashed src), regenerated by `nvfetcher`.
  # See ../../nvfetcher.toml.
  sources = pkgs.callPackage ../../_sources/generated.nix { };
in
{
  options.slippi-launcher = {
    enable = mkEnableOption "Install Slippi Launcher" // {
      default = true;
    };

    # Versions and hashes are pinned centrally by nvfetcher (../../nvfetcher.toml)
    # and updated via an automated PR. To pin a custom build, override the whole
    # package, e.g. `slippi-launcher.netplayPackage = pkgs.callPackage ./my.nix {};`.
    netplayPackage = mkOption {
      type = types.package;
      default = pkgs.callPackage ../../packages/slippi-netplay.nix {
        source = sources.netplay;
      };
      defaultText = literalExpression "the Slippi Netplay build pinned by this flake";
      description = "The Slippi Netplay package to install.";
    };

    netplayBetaPackage = mkOption {
      type = types.package;
      default = pkgs.callPackage ../../packages/slippi-netplay-beta.nix {
        source = sources.netplay-beta;
      };
      defaultText = literalExpression "the Slippi Netplay (Mainline beta) build pinned by this flake";
      description = "The Slippi Netplay (Mainline beta) package to install.";
    };

    playbackPackage = mkOption {
      type = types.package;
      default = pkgs.callPackage ../../packages/slippi-playback.nix {
        source = sources.playback;
      };
      defaultText = literalExpression "the Slippi Playback build pinned by this flake";
      description = "The Slippi Playback package to install.";
    };

    launcherPackage = mkOption {
      type = types.package;
      default = pkgs.callPackage ../../packages/slippi-launcher.nix {
        source = sources.launcher;
      };
      defaultText = literalExpression "the Slippi Launcher build pinned by this flake";
      description = "The Slippi Launcher package to install.";
    };

    isoPath = mkOption {
      default = "";
      type = types.str;
      description = "The path to an NTSC Melee ISO.";
    };
    useNetplayBeta = mkEnableOption "Use the mainline Dolphin instead of the stable version." // {
      default = false;
    };

    launchMeleeOnPlay = mkEnableOption "Launch Melee in Dolphin when the Play button is pressed." // {
      default = true;
    };

    enableJukebox =
      mkEnableOption "Enable in-game music via Slippi Jukebox. Incompatible with WASAPI."
      // {
        default = true;
      };

    rootSlpPath = mkOption {
      default = "${config.home.homeDirectory}/Slippi";
      type = types.str;
      description = "The folder where your SLP replays should be saved.";
    };

    useMonthlySubfolders = mkEnableOption "Save replays to monthly subfolders";

    spectateSlpPath = mkOption {
      default = "${cfg.rootSlpPath}/Spectate";
      type = types.nullOr types.str;
      description = "The folder where spectated games should be saved.";
    };

    extraSlpPaths = mkOption {
      default = [ ];
      type = types.listOf types.str;
      description = "Choose any additional SLP directories that should show up in the replay browser.";
    };
  };
  config = mkIf cfg.enable (
    let
      cfgNetplayPackage = cfg.netplayPackage;
      cfgNetplayBetaPackage = cfg.netplayBetaPackage;
      cfgPlaybackPackage = cfg.playbackPackage;
      cfgLauncherPackage = cfg.launcherPackage;
    in
    {
      home.packages = [ cfgLauncherPackage ];
      home.file.".config/Slippi Launcher/netplay/Slippi_Online-x86_64.AppImage" = {
        source = "${lib.getExe cfgNetplayPackage}";
        recursive = false;
      };
      home.file.".config/Slippi Launcher/netplay/Sys" = {
        source = "${cfgNetplayPackage.raw-zip}/Sys";
        recursive = false;
      };
      home.file.".config/Slippi Launcher/netplay-beta/Slippi_Netplay_Mainline-x86_64.AppImage" = {
        source = "${lib.getExe cfgNetplayBetaPackage}";
        recursive = false;
      };
      home.file.".config/Slippi Launcher/netplay-beta/Sys" = {
        source = "${cfgNetplayBetaPackage.raw-zip}/Sys";
        recursive = false;
      };
      home.file.".config/Slippi Launcher/playback/Slippi_Playback-x86_64.AppImage" = {
        source = "${lib.getExe cfgPlaybackPackage}";
        recursive = false;
      };
      home.file.".config/Slippi Launcher/playback/Sys" = {
        source = "${cfgPlaybackPackage.raw-zip}/Sys";
        recursive = false;
      };

      xdg = {
        mimeApps.defaultApplications = {
          "application/x-slippi" = "slippi-launcher.desktop";
        };
        dataFile."mime/packages/x-slippi.xml".text = ''
          <?xml version="1.0" encoding="UTF-8"?>
          <mime-info xmlns="http://www.freedesktop.org/standards/shared-mime-info">
            <mime-type type="application/x-slippi">
              <comment>Slippi Replay</comment>
              <glob pattern="*.slp"/>
              <icon name="slippi-launcher"/>
            </mime-type>
          </mime-info>
        '';
      };

      # Use an activation script instead of xdg.configFile so the settings
      # file is mutable. The launcher needs to write to it (e.g. login
      # credentials). Nix-managed settings are merged on each activation,
      # preserving any extra keys the launcher has written.
      home.activation.slippiLauncherSettings =
        let
          jsonFormat = pkgs.formats.json { };
          settingsFile = jsonFormat.generate "slippi-config" {
            settings = {
              isoPath = cfg.isoPath;

              launchMeleeOnPlay = cfg.launchMeleeOnPlay;
              enableJukebox = cfg.enableJukebox;
              useNetplayBeta = cfg.useNetplayBeta;

              rootSlpPath = cfg.rootSlpPath;
              useMonthlySubfolders = cfg.useMonthlySubfolders;
              spectateSlpPath = cfg.spectateSlpPath;
              extraSlpPaths = cfg.extraSlpPaths;

              # The launcher ignores netplayDolphinPath/playbackDolphinPath; it
              # always looks for AppImages under ~/.config/Slippi Launcher/{netplay,playback}/.
              # The home.file symlinks above are what actually prevent downloads.
              autoUpdateLauncher = false;
            };
          };
        in
        lib.hm.dag.entryAfter [ "writeBoundary" ] ''
          slippi_dir="${config.xdg.configHome}/Slippi Launcher"
          slippi_settings="$slippi_dir/Settings"

          mkdir -p "$slippi_dir"

          # Remove stale symlink from previous module version
          if [ -L "$slippi_settings" ]; then
            rm "$slippi_settings"
          fi

          if [ -f "$slippi_settings" ]; then
            # Merge existing settings with Nix-managed settings (Nix wins on conflicts)
            ${pkgs.jq}/bin/jq -s '.[0] * .[1]' \
              "$slippi_settings" \
              "${settingsFile}" > "$slippi_settings.tmp"
            mv "$slippi_settings.tmp" "$slippi_settings"
          else
            cp "${settingsFile}" "$slippi_settings"
            chmod u+w "$slippi_settings"
          fi
        '';
    }
  );
}
